export const typeOfClothes = [
  { id: 1, name: "áo" },
  { id: 1, name: "quần" },
  { id: 1, name: "túi" },
  { id: 1, name: "mũ" },
  { id: 1, name: "váy" },
];
export const clothes = [
  {
    id: 1,
    typeId: 2,
    imgURL:
      "https://cdn.ssstutter.com/products/po0EUQXd52Ks47dT/082022/1659516370765.jpeg",
    name: "Gray w-pants",
    price: "299.000",
    forMan: true,
    new: true,
    percentDiscount: 10,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 2,
    typeId: 1,
    imgURL:
      "https://cdn.ssstutter.com/products/po0EUQXd52Ks47dT/062022/1656562214790.jpeg",
    name: "Young Green",
    price: "199.000",
    forMan: true,
    new: true,
    percentDiscount: 25,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 3,
    typeId: 1,
    imgURL:
      "https://cdn.ssstutter.com/products/po0EUQXd52Ks47dT/072022/1657880260092.jpeg",
    name: "W Shirt",
    price: "399.000",
    forMan: true,
    new: true,
    percentDiscount: 18,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "navy",
    ],
  },
  {
    id: 4,
    typeId: 1,
    imgURL:
      "https://cdn.ssstutter.com/products/po0EUQXd52Ks47dT/082022/1659513986190.jpeg",
    name: "Jack Lane Shirt",
    price: "329.000",
    forMan: true,
    new: true,
    percentDiscount: 9,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 5,
    typeId: 1,
    imgURL: "https://cf.shopee.vn/file/bd7a93b3d0ff5ab27db7c881f54224df",
    name: "W Black",
    price: "599.000",
    forMan: true,
    new: false,
    percentDiscount: 7,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 6,
    typeId: 1,
    imgURL: "https://cf.shopee.vn/file/3b254004d039877f2118877981ee91a3",
    name: "Ss Highway",
    price: "699.000",
    forMan: true,
    new: true,
    percentDiscount: 10,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 7,
    typeId: 1,
    imgURL:
      "https://product.hstatic.net/1000348721/product/3x2a1425_6a217cbc03d94993936f30e4b248718b_grande.jpg",
    name: "BOTANIC SHIRT",
    price: "699.000",
    forMan: true,
    new: true,
    percentDiscount: 8,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 8,
    typeId: 1,
    imgURL:
      "https://product.hstatic.net/1000348721/product/img_6593_50393fcdb4274493a8518fa4cabfc752_master.jpg",
    name: "AEFIT SHIRT",
    price: "799.000",
    forMan: true,
    new: false,
    percentDiscount: 30,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 9,
    typeId: 1,
    imgURL:
      "https://product.hstatic.net/1000348721/product/dsc_6618_91a4ff3abee2449aa054980cff581cef_master.jpg",
    name: "4PIECES JACKET",
    price: "999.000",
    forMan: true,
    new: true,
    percentDiscount: 10,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "blue",
      "grey",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 10,
    typeId: 1,
    imgURL:
      "https://product.hstatic.net/1000348721/product/dsc_7578__1__064e74485f224f9986e26514c6550242_master.jpg",
    name: "AURORA VARSITY",
    price: "1.299.000",
    forMan: true,
    new: false,
    percentDiscount: 60,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "navy",
    ],
  },
  {
    id: 11,
    typeId: 1,
    imgURL:
      "https://cdn.ssstutter.com/products/po0EUQXd52Ks47dT/062022/1655785508834.jpeg",
    name: "S blz set",
    price: "199.000",
    forMan: false,
    new: false,
    percentDiscount: 50,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 12,
    typeId: 5,
    imgURL:
      "https://cdn.ssstutter.com/products/nCRHI1bpbr1ZIsxG/062022/1655468731414.jpeg",
    name: "MilkTea Split",
    price: "199.000",
    forMan: false,
    new: true,
    percentDiscount: 0,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 13,
    typeId: 1,
    imgURL:
      "https://cdn.ssstutter.com/products/nCRHI1bpbr1ZIsxG/062022/1655460355573.jpeg",
    name: "ViVi m-shirt",
    price: "339.000",
    forMan: false,
    new: true,
    percentDiscount: 30,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
      "navy",
    ],
  },
  {
    id: 14,
    typeId: 1,
    imgURL:
      "https://cdn.ssstutter.com/products/po0EUQXd52Ks47dT/062022/1655785694477.jpeg",
    name: "Unum tank",
    price: "299.000",
    forMan: false,
    new: false,
    percentDiscount: 0,
    color: ["yellow", "green", "black", "white", "brown", "grey", "fuchsia"],
  },
  {
    id: 15,
    typeId: 2,
    imgURL:
      "https://cdn.ssstutter.com/products/nCRHI1bpbr1ZIsxG/082022/1659495077983.jpeg",
    name: "Lace pants",
    price: "299.000",
    forMan: false,
    new: true,
    percentDiscount: 0,
    color: ["yellow", "green", "black", "aqua", "fuchsia", "navy"],
  },
  {
    id: 16,
    typeId: 2,
    imgURL:
      "https://cdn.ssstutter.com/products/6ZNKfc2866GyPhOg/102021/1634109382551.jpeg",
    name: "Sumer pant",
    price: "99.000",
    forMan: false,
    new: true,
    percentDiscount: 0,
    color: ["yellow", "green", "black", "white"],
  },
  {
    id: 17,
    typeId: 4,
    imgURL:
      "https://cdn.ssstutter.com/products/nCRHI1bpbr1ZIsxG/052022/1651644553705.jpeg",
    name: "Hat SSz-1",
    price: "299.000",
    forMan: false,
    new: true,
    percentDiscount: 20,
    color: [
      "yellow",
      "green",
      "black",
      "white",
      "brown",
      "blue",
      "grey",
      "aqua",
      "fuchsia",
    ],
  },
  {
    id: 18,
    typeId: 3,
    imgURL:
      "https://cdn.ssstutter.com/products/nCRHI1bpbr1ZIsxG/072022/1658121997644.jpeg",
    name: "Milk bag",
    price: "259.000",
    forMan: false,
    new: true,
    percentDiscount: 10,
    color: ["yellow", "green", "black", "white", "fuchsia", "navy"],
  },
  {
    id: 19,
    typeId: 3,
    imgURL:
      "https://cdn.ssstutter.com/products/nCRHI1bpbr1ZIsxG/072022/1657893713557.jpeg",
    name: "White SLux",
    price: "799.000",
    forMan: false,
    new: true,
    percentDiscount: 0,
    color: ["black", "white"],
  },
  {
    id: 20,
    typeId: 1,
    imgURL:
      "https://5.imimg.com/data5/TV/IU/MY-67054716/sassy-girl-t-shirt-with-tie-up-cutout-500x500.jpg",
    name: "BI BQ",
    price: "389.000",
    forMan: false,
    new: false,
    percentDiscount: 10,
    color: ["yellow", "green", "black", "white", "brown", "blue", "navy"],
  },
  {
    id: 21,
    typeId: 1,
    imgURL:
      "https://cdn.ssstutter.com/products/po0EUQXd52Ks47dT/062022/1655470074135.jpeg",
    name: "BzI Pant",
    price: "489.000",
    forMan: true,
    new: false,
    percentDiscount: 13,
    color: ["green", "black", "white", "brown"],
  },
];
